---
title: "Ações da sua carteira"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library (tidyquant)
library (dplyr)
library (ggplot2)
library (plotly)
library (DT)

prices <- read.csv("C:/Users/Milen/OneDrive/Documents/acoesmonitoramento/prices.csv") %>%
  mutate(date = as.Date(date))

tabela_periodo <- data.frame(
  periodo = c("1M", "6M", "1A", "10A"),
  dias = c(30, 180, 365, 3650)
)

colours = c(
  "KLBN4" = "green", "BBSE3" = "yellow", "SAPR4" = "blue", "ALUP11" = "cyan",
  "CPLE6" = "grey", "TAEE4" = "black", "SMTO3" = "pink",
  "GGBR4" = "red", "WEGE3" = "orange", "AMBP3" = "purple"
)

```

Column {.sidebar}
-----------------------------------------------------------------------



```{r}
selectInput(
  "acao", label = "Escolha sua ação",
  choices = c(
    "KLBN4", "BBSE3", "SAPR4", "ALUP11", "CPLE6", 
    "TAEE4", "SMTO3", "GGBR4", "WEGE3", "AMBP3"
  ))
selectInput(
  "periodo", label = "Escolha o período",
  choices = c("1M", "6M", "1A", "10A")
)
```

Row {data-width=500}
-----------------------------------------------------------------------

### Tendência

```{r}
renderPlotly({
  periodo <- Sys.Date() - filter(tabela_periodo, periodo ==   input$periodo)$dias
  
  prices %>%
    filter(date >= periodo, symbol == input$acao) %>%
    ggplot() + 
    aes(x= date, y = adjusted, color = symbol) +
    geom_line() +
    scale_color_manual(values = colours) +
    labs(x= "", y ="Cotação") +
    ggtitle(label = input$acao) +
    theme(
      panel.background = element_blank(),
      plot.title = element_text(size=22),
      legend.position = "none"
    )

})

```

### Todas as tendências

```{r}
renderPlotly({
  periodo <- Sys.Date() - filter(tabela_periodo, periodo == input$periodo)$dias
  
  prices %>%
    filter(date >= periodo) %>%
    ggplot() +
    aes(x= date, y = adjusted, color = symbol) +
    geom_line(size = 1.1) +
    scale_color_manual(values = colours) +
    labs(x= "", y = "Cotação", color = "Ação") +
    theme(panel.background = element_blank())
}
  
)

```

Row {data-width=500}
-----------------------------------------------------------------------

### Cotações

```{r}
renderDataTable({
  periodo <- Sys.Date() - filter(tabela_periodo, periodo == input$periodo)$dias
  
  prices %>%
    filter(date >= periodo, symbol == input$acao) %>%
    mutate(across(where(is.double), round, digits = 2)) %>%
    arrange(desc(date)) %>%
    rename(
      Ação = symbol,
      Data = date,
      Abertura = open,
      Máximo = high,
      Mínimo = low,
      Fechamento = close,
      Volume = volume,
      Ajustado = adjusted
    ) %>%
    datatable(rownames = FALSE)
}
)

```

